export const SIGNUP_SET_USER_EMAIL = 'SIGNUP_SET_USER_EMAIL';
export const SIGNUP_SET_USER_PASSWORD = 'SIGNUP_SET_USER_PASSWORD';
export const SIGNUP_SET_USER_PASSWORD = 'SIGNUP_SET_USER_PASSWORD';
export const SIGNUP_SET_USER_PASSWORD = 'SIGNUP_SET_USER_PASSWORD';
